services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: safepay_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./core-api:/var/www:delegated
      - app_vendor:/var/www/vendor
    networks:
      - safepay-net
    depends_on:
      - db
      - redis
      - kafka

  worker:
    build:
      context: .
      dockerfile: docker/php/Dockerfile    
    #container_name: safepay_worker comentado para permitir multiplas inst√¢ncias
    restart: always 
    working_dir: /var/www    
    command: /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
    networks:
      - safepay-net
    depends_on:
      - db
      - rabbitmq
      - redis      
    volumes:
      - ./core-api:/var/www:delegated
      - app_vendor:/var/www/vendor
      - ./docker/php/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    env_file: ./core-api/.env

  reverb:
    image: safepay-project-app:latest 
    container_name: safepay_reverb
    restart: always
    working_dir: /var/www
    # Comando para iniciar o servidor WebSocket
    command: php artisan reverb:start --host="0.0.0.0" --port=8080
    ports:
      - "8080:8080"
    networks:
      - safepay-net
    volumes:
      - ./core-api:/var/www:delegated
      - app_vendor:/var/www/vendor
    depends_on:
      - redis
      - app

  nginx:
    image: nginx:alpine
    container_name: safepay_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./core-api:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - safepay-net
    depends_on:
      - app

  db:
    image: postgres:16
    container_name: safepay_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: safepay
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - safepay-net

  redis:
    image: redis:alpine
    container_name: safepay_redis
    ports:
      - "6379:6379"
    networks:
      - safepay-net

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: safepay_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - safepay-net

  kafka:
    image: apache/kafka:4.1.1
    container_name: safepay_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      
      # Listeners
      # 9092: Laravel, Kafdrop
      # 9093: Controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - safepay-net

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: safepay_kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
      JVM_OPTS: "-Xms32M -Xmx64M"
    depends_on:
      - kafka
    networks:
      - safepay-net

volumes:
  pgdata:
  app_vendor:

networks:
  safepay-net:
    driver: bridge